overlord-bot/Overlord

bot.py, cogs/general/startup.py
In order to add a slash command in a cog:
```
@discord.app_commands.command(name="name")
async def func_name(self, interaction: discord.Interaction) -> None:
await interaction.response.send_message("Hi!")
```
=> Slash commands now sync

cogs/minigames/empty.py, cogs/minigames/word_game.py
Add beginning code to wordle clone
=> Wordle clone

cogs/webcrawling/anime_scraper.py, cogs/webcrawling/rpi_catalog_scraper.py, cogs/webcrawling/rpi_program_scraper.py
writes parsed catalog data to JSON file
=> Merge webcrawling

README.md
merging from degree planner's branch into degree planner
=> testing branch merge from degree planner branch into degree planner

cogs/bash/Dockerfile, cogs/bash/bash.py
Initial implementation for the cog that allows running of Linux in Discord using Docker containers.
=> Linux Docker container cog implementation

cogs/degree planner/degree_planner.py, cogs/degree planner/schedule.py
Scheduler mode user interface
Commands in scheduler mode: (!dp then 9)
add, <semester>, <courses>
remove, <semester>, <courses>
reschedule
print
=> Added chat UI

cogs/general/help_command.py
Implement a custom help command that uses an Embed object.
=> Help command

bot.py, cogs/finance/yahoo_finance.py
- Command to get extended stock info added
- Style changes in bot.py
=> Add extended stock information commands

.gitignore, cogs/github scraper/commits_scraper.py
Command added to web scrape all commits from a user in the main branch of a GitHub Repository
=> GitHub scraper

bot.py, cogs/chatbot/README.md, cogs/chatbot/basic_chat - Andy.py, cogs/chatbot/basic_chat - Bijun.py, cogs/chatbot/basic_chat - Tim.py, cogs/chatbot/chatbot_README.txt
fix tim-chat.py error in loading
add new readme
=> Over lord chatbot tim & bj & andy

cogs/github scraper/commits_scraper.py
Vitisadi: added scraper for other branches
=> GitHub commits

cogs/math/README.md
- Explanation of functions and oddities
=> Closes Add README.md for Math cog #39

bot.py
bot.py uninitialized variable fixed
=> emergency bug fix `(*>﹏<*)′

cogs/webcrawling/catalog_results.json, cogs/webcrawling/class_results.json, cogs/webcrawling/rpi_catalog_scraper.py
- prevents "Contact, Lecture or Lab Hours" from being appended to the credit hours variable when parsing
=> Bug fix related to issue 80

cogs/information_scrapers/anime_scraper.py
- !anime can search for titles longer than 2 words now
=> Bug fix related to issue #35

cogs/degree-planner/catalog.py, cogs/degree-planner/course.py, cogs/degree-planner/degree.py, cogs/degree-planner/degree_planner.py, cogs/degree-planner/rules.py, cogs/degree-planner/schedule.py, cogs/degree-planner/user.py
at the cost of 29 sanity points I managed to finish this feature lmao
basically now you can type "fulfillment" while in scheduling mode and it checks your taken courses against all the requirements defined by rules stored in each degree.
You get to set your degree using the command degree, <degree name> inside scheduling mode
=> degree requirement checking prototype done q(≧▽≦q)

cogs/moderation/README.md
=> Create README.md for moderation cog

cogs/degree-planner/catalog.py, cogs/degree-planner/degree_planner.py
emergency patch otherwise every chat message will be interpreted as a command lmao
=> requires !dp before every line of commands

cogs/degree-planner/catalog.py, cogs/degree-planner/command.py, cogs/degree-planner/degree_planner.py, cogs/degree-planner/output.py, cogs/degree-planner/parse.py, cogs/degree-planner/schedule.py, cogs/degree-planner/search.py, cogs/degree-planner/user.py
degree_planner.py documented, will work on the other files later, but for now degree_planner.py is the most important one since it acts as an API
Put parsing function in it's own file parse.py (not a class, just moved it separately to make things tidier). 
Removed debugging print statements, now only print to console when there's an error, during maintenance operations such as test or import, or reporting user message events.
=> Feature/degree planner cleaning up code, documentation notes

cogs/degree-planner/degree_planner.py
=> casting error bug fix

cogs/degree-planner/degree_planner.py, cogs/degree-planner/output.py, cogs/degree-planner/user.py
I'll add more detailed documentation later but for now the functions are at least not a total mess
=> Cleaned up output.py, embed color now based on user color

cogs/general/common_events.py, cogs/math/math.py, cogs/minigames/tictactoe/tictactoe.py
Other commands will have to be decorated with @commands.cooldown(...) on an individual basis
=> Addresses #102 for tic-tac-toe and math
